//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramacionIV.ServiceReferenceUniversidad {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profesor", Namespace="http://schemas.datacontract.org/2004/07/ProgramacionIV.Entidades")]
    [System.SerializableAttribute()]
    public partial class Profesor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ProgramacionIV.ServiceReferenceUniversidad.Curso> CursoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EspecialidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ProgramacionIV.ServiceReferenceUniversidad.Matricula> MatriculasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProfesorIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ProgramacionIV.ServiceReferenceUniversidad.Curso> Cursoes {
            get {
                return this.CursoesField;
            }
            set {
                if ((object.ReferenceEquals(this.CursoesField, value) != true)) {
                    this.CursoesField = value;
                    this.RaisePropertyChanged("Cursoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Especialidad {
            get {
                return this.EspecialidadField;
            }
            set {
                if ((object.ReferenceEquals(this.EspecialidadField, value) != true)) {
                    this.EspecialidadField = value;
                    this.RaisePropertyChanged("Especialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ProgramacionIV.ServiceReferenceUniversidad.Matricula> Matriculas {
            get {
                return this.MatriculasField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculasField, value) != true)) {
                    this.MatriculasField = value;
                    this.RaisePropertyChanged("Matriculas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProfesorID {
            get {
                return this.ProfesorIDField;
            }
            set {
                if ((this.ProfesorIDField.Equals(value) != true)) {
                    this.ProfesorIDField = value;
                    this.RaisePropertyChanged("ProfesorID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Curso", Namespace="http://schemas.datacontract.org/2004/07/ProgramacionIV.Entidades")]
    [System.SerializableAttribute()]
    public partial class Curso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CursoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProgramacionIV.ServiceReferenceUniversidad.Materia MateriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MateriaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ProgramacionIV.ServiceReferenceUniversidad.Matricula> MatriculasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProgramacionIV.ServiceReferenceUniversidad.Profesor ProfesorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProfesorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte SemestreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Anio {
            get {
                return this.AnioField;
            }
            set {
                if ((this.AnioField.Equals(value) != true)) {
                    this.AnioField = value;
                    this.RaisePropertyChanged("Anio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CursoID {
            get {
                return this.CursoIDField;
            }
            set {
                if ((this.CursoIDField.Equals(value) != true)) {
                    this.CursoIDField = value;
                    this.RaisePropertyChanged("CursoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProgramacionIV.ServiceReferenceUniversidad.Materia Materia {
            get {
                return this.MateriaField;
            }
            set {
                if ((object.ReferenceEquals(this.MateriaField, value) != true)) {
                    this.MateriaField = value;
                    this.RaisePropertyChanged("Materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MateriaID {
            get {
                return this.MateriaIDField;
            }
            set {
                if ((this.MateriaIDField.Equals(value) != true)) {
                    this.MateriaIDField = value;
                    this.RaisePropertyChanged("MateriaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ProgramacionIV.ServiceReferenceUniversidad.Matricula> Matriculas {
            get {
                return this.MatriculasField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculasField, value) != true)) {
                    this.MatriculasField = value;
                    this.RaisePropertyChanged("Matriculas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProgramacionIV.ServiceReferenceUniversidad.Profesor Profesor {
            get {
                return this.ProfesorField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfesorField, value) != true)) {
                    this.ProfesorField = value;
                    this.RaisePropertyChanged("Profesor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProfesorID {
            get {
                return this.ProfesorIDField;
            }
            set {
                if ((this.ProfesorIDField.Equals(value) != true)) {
                    this.ProfesorIDField = value;
                    this.RaisePropertyChanged("ProfesorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Semestre {
            get {
                return this.SemestreField;
            }
            set {
                if ((this.SemestreField.Equals(value) != true)) {
                    this.SemestreField = value;
                    this.RaisePropertyChanged("Semestre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Matricula", Namespace="http://schemas.datacontract.org/2004/07/ProgramacionIV.Entidades")]
    [System.SerializableAttribute()]
    public partial class Matricula : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProgramacionIV.ServiceReferenceUniversidad.Curso CursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CursoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProgramacionIV.ServiceReferenceUniversidad.Estudiante EstudianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstudianteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaMatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatriculaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> NotaFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProgramacionIV.ServiceReferenceUniversidad.Profesor ProfesorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RegistradoPorProfesorIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProgramacionIV.ServiceReferenceUniversidad.Curso Curso {
            get {
                return this.CursoField;
            }
            set {
                if ((object.ReferenceEquals(this.CursoField, value) != true)) {
                    this.CursoField = value;
                    this.RaisePropertyChanged("Curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CursoID {
            get {
                return this.CursoIDField;
            }
            set {
                if ((this.CursoIDField.Equals(value) != true)) {
                    this.CursoIDField = value;
                    this.RaisePropertyChanged("CursoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProgramacionIV.ServiceReferenceUniversidad.Estudiante Estudiante {
            get {
                return this.EstudianteField;
            }
            set {
                if ((object.ReferenceEquals(this.EstudianteField, value) != true)) {
                    this.EstudianteField = value;
                    this.RaisePropertyChanged("Estudiante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstudianteID {
            get {
                return this.EstudianteIDField;
            }
            set {
                if ((this.EstudianteIDField.Equals(value) != true)) {
                    this.EstudianteIDField = value;
                    this.RaisePropertyChanged("EstudianteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaMatricula {
            get {
                return this.FechaMatriculaField;
            }
            set {
                if ((this.FechaMatriculaField.Equals(value) != true)) {
                    this.FechaMatriculaField = value;
                    this.RaisePropertyChanged("FechaMatricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatriculaID {
            get {
                return this.MatriculaIDField;
            }
            set {
                if ((this.MatriculaIDField.Equals(value) != true)) {
                    this.MatriculaIDField = value;
                    this.RaisePropertyChanged("MatriculaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NotaFinal {
            get {
                return this.NotaFinalField;
            }
            set {
                if ((this.NotaFinalField.Equals(value) != true)) {
                    this.NotaFinalField = value;
                    this.RaisePropertyChanged("NotaFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProgramacionIV.ServiceReferenceUniversidad.Profesor Profesor {
            get {
                return this.ProfesorField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfesorField, value) != true)) {
                    this.ProfesorField = value;
                    this.RaisePropertyChanged("Profesor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RegistradoPorProfesorID {
            get {
                return this.RegistradoPorProfesorIDField;
            }
            set {
                if ((this.RegistradoPorProfesorIDField.Equals(value) != true)) {
                    this.RegistradoPorProfesorIDField = value;
                    this.RaisePropertyChanged("RegistradoPorProfesorID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Materia", Namespace="http://schemas.datacontract.org/2004/07/ProgramacionIV.Entidades")]
    [System.SerializableAttribute()]
    public partial class Materia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreditosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ProgramacionIV.ServiceReferenceUniversidad.Curso> CursoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MateriaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Creditos {
            get {
                return this.CreditosField;
            }
            set {
                if ((this.CreditosField.Equals(value) != true)) {
                    this.CreditosField = value;
                    this.RaisePropertyChanged("Creditos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ProgramacionIV.ServiceReferenceUniversidad.Curso> Cursoes {
            get {
                return this.CursoesField;
            }
            set {
                if ((object.ReferenceEquals(this.CursoesField, value) != true)) {
                    this.CursoesField = value;
                    this.RaisePropertyChanged("Cursoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MateriaID {
            get {
                return this.MateriaIDField;
            }
            set {
                if ((this.MateriaIDField.Equals(value) != true)) {
                    this.MateriaIDField = value;
                    this.RaisePropertyChanged("MateriaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estudiante", Namespace="http://schemas.datacontract.org/2004/07/ProgramacionIV.Entidades")]
    [System.SerializableAttribute()]
    public partial class Estudiante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstudianteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ProgramacionIV.ServiceReferenceUniversidad.Matricula> MatriculasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstudianteID {
            get {
                return this.EstudianteIDField;
            }
            set {
                if ((this.EstudianteIDField.Equals(value) != true)) {
                    this.EstudianteIDField = value;
                    this.RaisePropertyChanged("EstudianteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ProgramacionIV.ServiceReferenceUniversidad.Matricula> Matriculas {
            get {
                return this.MatriculasField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculasField, value) != true)) {
                    this.MatriculasField = value;
                    this.RaisePropertyChanged("Matriculas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceUniversidad.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ProgramacionIV.Servicios.CompositeType GetDataUsingDataContract(ProgramacionIV.Servicios.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ProgramacionIV.Servicios.CompositeType> GetDataUsingDataContractAsync(ProgramacionIV.Servicios.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GuardarProfesor", ReplyAction="http://tempuri.org/IService1/GuardarProfesorResponse")]
        string GuardarProfesor(ProgramacionIV.ServiceReferenceUniversidad.Profesor profesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GuardarProfesor", ReplyAction="http://tempuri.org/IService1/GuardarProfesorResponse")]
        System.Threading.Tasks.Task<string> GuardarProfesorAsync(ProgramacionIV.ServiceReferenceUniversidad.Profesor profesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProbarConexion", ReplyAction="http://tempuri.org/IService1/ProbarConexionResponse")]
        string ProbarConexion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProbarConexion", ReplyAction="http://tempuri.org/IService1/ProbarConexionResponse")]
        System.Threading.Tasks.Task<string> ProbarConexionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarEstudiante", ReplyAction="http://tempuri.org/IService1/InsertarEstudianteResponse")]
        string InsertarEstudiante(ProgramacionIV.ServiceReferenceUniversidad.Estudiante estudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarEstudiante", ReplyAction="http://tempuri.org/IService1/InsertarEstudianteResponse")]
        System.Threading.Tasks.Task<string> InsertarEstudianteAsync(ProgramacionIV.ServiceReferenceUniversidad.Estudiante estudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerEstudiantes", ReplyAction="http://tempuri.org/IService1/ObtenerEstudiantesResponse")]
        System.Collections.Generic.List<ProgramacionIV.ServiceReferenceUniversidad.Estudiante> ObtenerEstudiantes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerEstudiantes", ReplyAction="http://tempuri.org/IService1/ObtenerEstudiantesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProgramacionIV.ServiceReferenceUniversidad.Estudiante>> ObtenerEstudiantesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BorrarEstudiante", ReplyAction="http://tempuri.org/IService1/BorrarEstudianteResponse")]
        string BorrarEstudiante(int estudianteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BorrarEstudiante", ReplyAction="http://tempuri.org/IService1/BorrarEstudianteResponse")]
        System.Threading.Tasks.Task<string> BorrarEstudianteAsync(int estudianteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarEstudiante", ReplyAction="http://tempuri.org/IService1/ActualizarEstudianteResponse")]
        string ActualizarEstudiante(ProgramacionIV.ServiceReferenceUniversidad.Estudiante estudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarEstudiante", ReplyAction="http://tempuri.org/IService1/ActualizarEstudianteResponse")]
        System.Threading.Tasks.Task<string> ActualizarEstudianteAsync(ProgramacionIV.ServiceReferenceUniversidad.Estudiante estudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerEstudiantePorID", ReplyAction="http://tempuri.org/IService1/ObtenerEstudiantePorIDResponse")]
        ProgramacionIV.ServiceReferenceUniversidad.Estudiante ObtenerEstudiantePorID(int estudianteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerEstudiantePorID", ReplyAction="http://tempuri.org/IService1/ObtenerEstudiantePorIDResponse")]
        System.Threading.Tasks.Task<ProgramacionIV.ServiceReferenceUniversidad.Estudiante> ObtenerEstudiantePorIDAsync(int estudianteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarMateria", ReplyAction="http://tempuri.org/IService1/InsertarMateriaResponse")]
        string InsertarMateria(ProgramacionIV.ServiceReferenceUniversidad.Materia materia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarMateria", ReplyAction="http://tempuri.org/IService1/InsertarMateriaResponse")]
        System.Threading.Tasks.Task<string> InsertarMateriaAsync(ProgramacionIV.ServiceReferenceUniversidad.Materia materia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTodasLasMaterias", ReplyAction="http://tempuri.org/IService1/ObtenerTodasLasMateriasResponse")]
        System.Collections.Generic.List<ProgramacionIV.ServiceReferenceUniversidad.Materia> ObtenerTodasLasMaterias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTodasLasMaterias", ReplyAction="http://tempuri.org/IService1/ObtenerTodasLasMateriasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProgramacionIV.ServiceReferenceUniversidad.Materia>> ObtenerTodasLasMateriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BorrarMateria", ReplyAction="http://tempuri.org/IService1/BorrarMateriaResponse")]
        string BorrarMateria(int materiaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BorrarMateria", ReplyAction="http://tempuri.org/IService1/BorrarMateriaResponse")]
        System.Threading.Tasks.Task<string> BorrarMateriaAsync(int materiaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarMateria", ReplyAction="http://tempuri.org/IService1/ActualizarMateriaResponse")]
        string ActualizarMateria(ProgramacionIV.ServiceReferenceUniversidad.Materia materia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarMateria", ReplyAction="http://tempuri.org/IService1/ActualizarMateriaResponse")]
        System.Threading.Tasks.Task<string> ActualizarMateriaAsync(ProgramacionIV.ServiceReferenceUniversidad.Materia materia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerMateriaPorID", ReplyAction="http://tempuri.org/IService1/ObtenerMateriaPorIDResponse")]
        ProgramacionIV.ServiceReferenceUniversidad.Materia ObtenerMateriaPorID(int materiaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerMateriaPorID", ReplyAction="http://tempuri.org/IService1/ObtenerMateriaPorIDResponse")]
        System.Threading.Tasks.Task<ProgramacionIV.ServiceReferenceUniversidad.Materia> ObtenerMateriaPorIDAsync(int materiaID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ProgramacionIV.ServiceReferenceUniversidad.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ProgramacionIV.ServiceReferenceUniversidad.IService1>, ProgramacionIV.ServiceReferenceUniversidad.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ProgramacionIV.Servicios.CompositeType GetDataUsingDataContract(ProgramacionIV.Servicios.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ProgramacionIV.Servicios.CompositeType> GetDataUsingDataContractAsync(ProgramacionIV.Servicios.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string GuardarProfesor(ProgramacionIV.ServiceReferenceUniversidad.Profesor profesor) {
            return base.Channel.GuardarProfesor(profesor);
        }
        
        public System.Threading.Tasks.Task<string> GuardarProfesorAsync(ProgramacionIV.ServiceReferenceUniversidad.Profesor profesor) {
            return base.Channel.GuardarProfesorAsync(profesor);
        }
        
        public string ProbarConexion() {
            return base.Channel.ProbarConexion();
        }
        
        public System.Threading.Tasks.Task<string> ProbarConexionAsync() {
            return base.Channel.ProbarConexionAsync();
        }
        
        public string InsertarEstudiante(ProgramacionIV.ServiceReferenceUniversidad.Estudiante estudiante) {
            return base.Channel.InsertarEstudiante(estudiante);
        }
        
        public System.Threading.Tasks.Task<string> InsertarEstudianteAsync(ProgramacionIV.ServiceReferenceUniversidad.Estudiante estudiante) {
            return base.Channel.InsertarEstudianteAsync(estudiante);
        }
        
        public System.Collections.Generic.List<ProgramacionIV.ServiceReferenceUniversidad.Estudiante> ObtenerEstudiantes() {
            return base.Channel.ObtenerEstudiantes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProgramacionIV.ServiceReferenceUniversidad.Estudiante>> ObtenerEstudiantesAsync() {
            return base.Channel.ObtenerEstudiantesAsync();
        }
        
        public string BorrarEstudiante(int estudianteID) {
            return base.Channel.BorrarEstudiante(estudianteID);
        }
        
        public System.Threading.Tasks.Task<string> BorrarEstudianteAsync(int estudianteID) {
            return base.Channel.BorrarEstudianteAsync(estudianteID);
        }
        
        public string ActualizarEstudiante(ProgramacionIV.ServiceReferenceUniversidad.Estudiante estudiante) {
            return base.Channel.ActualizarEstudiante(estudiante);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarEstudianteAsync(ProgramacionIV.ServiceReferenceUniversidad.Estudiante estudiante) {
            return base.Channel.ActualizarEstudianteAsync(estudiante);
        }
        
        public ProgramacionIV.ServiceReferenceUniversidad.Estudiante ObtenerEstudiantePorID(int estudianteID) {
            return base.Channel.ObtenerEstudiantePorID(estudianteID);
        }
        
        public System.Threading.Tasks.Task<ProgramacionIV.ServiceReferenceUniversidad.Estudiante> ObtenerEstudiantePorIDAsync(int estudianteID) {
            return base.Channel.ObtenerEstudiantePorIDAsync(estudianteID);
        }
        
        public string InsertarMateria(ProgramacionIV.ServiceReferenceUniversidad.Materia materia) {
            return base.Channel.InsertarMateria(materia);
        }
        
        public System.Threading.Tasks.Task<string> InsertarMateriaAsync(ProgramacionIV.ServiceReferenceUniversidad.Materia materia) {
            return base.Channel.InsertarMateriaAsync(materia);
        }
        
        public System.Collections.Generic.List<ProgramacionIV.ServiceReferenceUniversidad.Materia> ObtenerTodasLasMaterias() {
            return base.Channel.ObtenerTodasLasMaterias();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProgramacionIV.ServiceReferenceUniversidad.Materia>> ObtenerTodasLasMateriasAsync() {
            return base.Channel.ObtenerTodasLasMateriasAsync();
        }
        
        public string BorrarMateria(int materiaID) {
            return base.Channel.BorrarMateria(materiaID);
        }
        
        public System.Threading.Tasks.Task<string> BorrarMateriaAsync(int materiaID) {
            return base.Channel.BorrarMateriaAsync(materiaID);
        }
        
        public string ActualizarMateria(ProgramacionIV.ServiceReferenceUniversidad.Materia materia) {
            return base.Channel.ActualizarMateria(materia);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarMateriaAsync(ProgramacionIV.ServiceReferenceUniversidad.Materia materia) {
            return base.Channel.ActualizarMateriaAsync(materia);
        }
        
        public ProgramacionIV.ServiceReferenceUniversidad.Materia ObtenerMateriaPorID(int materiaID) {
            return base.Channel.ObtenerMateriaPorID(materiaID);
        }
        
        public System.Threading.Tasks.Task<ProgramacionIV.ServiceReferenceUniversidad.Materia> ObtenerMateriaPorIDAsync(int materiaID) {
            return base.Channel.ObtenerMateriaPorIDAsync(materiaID);
        }
    }
}
